//
// Created by Андрей on 13/10/2023.
//

#ifndef LAB_03_CG_COURSE_PROGRAMM_OPENGL_ENCODEDSTRCUTSFUNCS_H_
#define LAB_03_CG_COURSE_PROGRAMM_OPENGL_ENCODEDSTRCUTSFUNCS_H_

#endif //LAB_03_CG_COURSE_PROGRAMM_OPENGL_ENCODEDSTRCUTSFUNCS_H_
